# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entry.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time


class Ui_Entry(object):
    def setupUi(self, Entry):
        Entry.setObjectName("Entry")
        Entry.resize(800, 600)
        Entry.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(Entry)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(130, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setMinimumSize(QtCore.QSize(400, 100))
        self.logo.setObjectName("logo")
        self.verticalLayout_2.addWidget(self.logo)
        spacerItem1 = QtWidgets.QSpacerItem(430, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(88, 398, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.capture = QtWidgets.QPushButton(self.centralwidget)
        self.capture.setMinimumSize(QtCore.QSize(200, 70))
        self.capture.setObjectName("capture")
        self.verticalLayout.addWidget(self.capture)
        spacerItem3 = QtWidgets.QSpacerItem(138, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.analyze = QtWidgets.QPushButton(self.centralwidget)
        self.analyze.setMinimumSize(QtCore.QSize(200, 70))
        self.analyze.setObjectName("analyze")
        self.verticalLayout.addWidget(self.analyze)
        spacerItem4 = QtWidgets.QSpacerItem(138, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.monitor = QtWidgets.QPushButton(self.centralwidget)
        self.monitor.setMinimumSize(QtCore.QSize(200, 70))
        self.monitor.setObjectName("monitor")
        self.verticalLayout.addWidget(self.monitor)
        spacerItem5 = QtWidgets.QSpacerItem(138, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setMinimumSize(QtCore.QSize(200, 70))
        self.exit.setObjectName("exit")
        self.verticalLayout.addWidget(self.exit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(97, 398, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.right_corner = QtWidgets.QLabel(self.centralwidget)
        self.right_corner.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.right_corner.setText("")
        self.right_corner.setObjectName("right_corner")
        self.horizontalLayout_2.addWidget(self.right_corner)
        spacerItem7 = QtWidgets.QSpacerItem(129, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        Entry.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Entry)
        self.statusbar.setObjectName("statusbar")
        Entry.setStatusBar(self.statusbar)

        self.capture.setIcon(QtGui.QIcon('static/capture.jpg'))
        self.capture.setIconSize(QtCore.QSize(50, 50))
        self.analyze.setIcon(QtGui.QIcon('static/analyze.jpg'))
        self.analyze.setIconSize(QtCore.QSize(50, 50))
        self.monitor.setIcon(QtGui.QIcon('static/monitor.jpg'))
        self.monitor.setIconSize(QtCore.QSize(50, 50))
        self.exit.setIcon(QtGui.QIcon('static/exit.jpg'))
        self.exit.setIconSize(QtCore.QSize(50, 50))

        self.retranslateUi(Entry)
        self.capture.clicked.connect(Entry.capture_on_clicked)
        self.analyze.clicked.connect(Entry.analyze_on_clicked)
        self.monitor.clicked.connect(Entry.monitor_on_clicked)
        self.exit.clicked.connect(Entry.exit_on_clicked)
        QtCore.QMetaObject.connectSlotsByName(Entry)

        self.capture.setStyleSheet('''
                    QPushButton{
                        border:none;
                        border-bottom:2px solid gray;
                        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                        color:green;
                        font-size:20px;
                        font-weight:bold;
                        height:40px;
                        padding-left:5px;
                        padding-right:10px;
                        text-align:left;
                    }
                    QPushButton:hover{
                        color:black;
                        border:1px solid #F3F3F5;
                        border-radius:10px;
                        background:LightGray;
                    }
                ''')
        self.analyze.setStyleSheet('''
                            QPushButton{
                                border:none;
                                border-bottom:2px solid gray;
                                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                                color:blue;
                                font-size:20px;
                                font-weight:bold;
                                height:40px;
                                padding-left:5px;
                                padding-right:10px;
                                text-align:left;
                            }
                            QPushButton:hover{
                                color:black;
                                border:1px solid #F3F3F5;
                                border-radius:10px;
                                background:LightGray;
                            }
                        ''')
        self.monitor.setStyleSheet('''
                            QPushButton{
                                border:none;
                                border-bottom:2px solid gray;
                                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                                color:orange;
                                font-size:20px;
                                font-weight:bold;
                                height:40px;
                                padding-left:5px;
                                padding-right:10px;
                                text-align:left;
                            }
                            QPushButton:hover{
                                color:black;
                                border:1px solid #F3F3F5;
                                border-radius:10px;
                                background:LightGray;
                            }
                        ''')
        self.exit.setStyleSheet('''
                            QPushButton{
                                border:none;
                                border-bottom:2px solid gray;
                                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                                color:red;
                                font-size:20px;
                                font-weight:bold;
                                height:40px;
                                padding-left:5px;
                                padding-right:10px;
                                text-align:left;
                            }
                            QPushButton:hover{
                                color:black;
                                border:1px solid #F3F3F5;
                                border-radius:10px;
                                background:LightGray;
                            }
                        ''')

    def retranslateUi(self, Entry):
        _translate = QtCore.QCoreApplication.translate
        Entry.setWindowTitle(_translate("Entry", "MainWindow"))
        self.logo.setWhatsThis(_translate("Entry", "<html><head/><body><p><br/></p></body></html>"))
        self.logo.setText(_translate("Entry", "<html><head/><body><p><img src=\"static/logo.png\" height=\"100\" width=\"430\"/></p></body></html>"))
        self.capture.setText(_translate("Entry", "         Capture       "))
        self.analyze.setText(_translate("Entry", "         Analyze       "))
        self.monitor.setText(_translate("Entry", "          Monitor      "))
        self.exit.setText(_translate("Entry", "             Exit   "))