# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ListDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListDialog(object):
    def setupUi(self, ListDialog):
        ListDialog.setObjectName("ListDialog")
        ListDialog.resize(757, 605)
        ListDialog.setMinimumSize(QtCore.QSize(757, 605))
        self.verticalLayout = QtWidgets.QVBoxLayout(ListDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ListDialog)
        self.label.setMinimumSize(QtCore.QSize(731, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listView = QtWidgets.QListView(ListDialog)
        self.listView.setMinimumSize(QtCore.QSize(733, 481))
        self.listView.setWordWrap(True)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(ListDialog)
        self.lineEdit.setMinimumSize(QtCore.QSize(271, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(ListDialog)
        self.pushButton.setMinimumSize(QtCore.QSize(101, 51))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(ListDialog)
        self.pushButton_2.setMinimumSize(QtCore.QSize(101, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(ListDialog)
        self.pushButton_3.setMinimumSize(QtCore.QSize(101, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(ListDialog)
        self.pushButton_4.setMinimumSize(QtCore.QSize(101, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        spacerItem = QtWidgets.QSpacerItem(13, 36, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ListDialog)
        self.pushButton.clicked.connect(ListDialog.func1)
        self.pushButton_2.clicked.connect(ListDialog.func2)
        self.pushButton_3.clicked.connect(ListDialog.func3)
        self.pushButton_4.clicked.connect(ListDialog.func4)
        self.lineEdit.returnPressed.connect(ListDialog.return_pressed)
        self.listView.doubleClicked['QModelIndex'].connect(ListDialog.item_double_clicked)
        QtCore.QMetaObject.connectSlotsByName(ListDialog)

    def retranslateUi(self, ListDialog):
        _translate = QtCore.QCoreApplication.translate
        ListDialog.setWindowTitle(_translate("ListDialog", "Dialog"))
        self.label.setText(_translate("ListDialog", "TextLabel"))
        self.pushButton.setText(_translate("ListDialog", "PushButton"))
        self.pushButton_2.setText(_translate("ListDialog", "PushButton"))
        self.pushButton_3.setText(_translate("ListDialog", "PushButton"))
        self.pushButton_4.setText(_translate("ListDialog", "PushButton"))
