# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Monitor(object):
    def setupUi(self, Monitor):
        Monitor.setObjectName("Monitor")
        Monitor.resize(1132, 595)
        Monitor.setMinimumSize(QtCore.QSize(1132, 595))
        self.gridLayout_2 = QtWidgets.QGridLayout(Monitor)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(Monitor)
        self.label.setMinimumSize(QtCore.QSize(1091, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.graphicsView = QChartView(Monitor)
        self.graphicsView.setMinimumSize(QtCore.QSize(761, 481))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Monitor)
        self.label_2.setMinimumSize(QtCore.QSize(91, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(Monitor)
        self.comboBox.setMinimumSize(QtCore.QSize(91, 30))
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Monitor)
        self.label_3.setMinimumSize(QtCore.QSize(91, 30))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Monitor)
        self.lineEdit.setMinimumSize(QtCore.QSize(191, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Monitor)
        self.label_4.setMinimumSize(QtCore.QSize(301, 161))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 3)
        self.pushButton = QtWidgets.QPushButton(Monitor)
        self.pushButton.setMinimumSize(QtCore.QSize(91, 41))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Monitor)
        self.pushButton_2.setMinimumSize(QtCore.QSize(91, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)

        self.retranslateUi(Monitor)
        self.comboBox.currentIndexChanged['int'].connect(Monitor.iface_changed)
        self.lineEdit.returnPressed.connect(Monitor.filter_changed)
        self.pushButton.clicked.connect(Monitor.start_on_clicked)
        self.pushButton_2.clicked.connect(Monitor.clear_on_clicked)
        QtCore.QMetaObject.connectSlotsByName(Monitor)

    def retranslateUi(self, Monitor):
        _translate = QtCore.QCoreApplication.translate
        Monitor.setWindowTitle(_translate("Monitor", "Dialog"))
        self.label.setText(_translate("Monitor", "TextLabel"))
        self.label_2.setText(_translate("Monitor", "网络接口"))
        self.label_3.setText(_translate("Monitor", "过滤器"))
        self.label_4.setText(_translate("Monitor", "TextLabel"))
        self.pushButton.setText(_translate("Monitor", "start"))
        self.pushButton_2.setText(_translate("Monitor", "clear"))
from PyQt5.QtChart import QChartView
